### ISSUE TITLE
tf_analyzer default parameter

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#32]
I tried to run `python bin/tf_analyzer.py`

And got the following error message:
```
  File "<stdin>", line 17
    args = parser.parse_args(['-d', '/mnt/workspace/hschult/jlu-bda-2020/data/download', '-o', 'linking_table.csv', '-b', '105kc', '1182-4h', '1205-lu', '129 mouse strain', '129/sv', '129p1/rej', '129s1/svimj', '129s6', '129x1/svj', '129xc57bl/6', '143b', '1a2', '1st arch mandibular component', '1st arch mandibular ectoderm', '1st arch mandibular endoderm', '1st arch mandibular mesenchyme', '1st arch mandibular mesenchyme from head mesenchyme', '1st arch mandibular mesenchyme from neural crest', '1st arch maxillary component', '1st arch maxillary ectoderm', '1st arch maxillary endoderm', '1st arch maxillary mesenchyme', '1st arch maxillary mesenchyme from head mesenchyme', '1st arch maxillary mesenchyme from neural crest', '1st arch maxillary-mandibular cleft', '1st arch mesenchyme' ...

SyntaxError: invalid syntax
Warning message:
In if (grepl("^\\{", output)) { :
  the condition has length > 1 and only the first element will be used
Error in fread(file = csv_file, header = TRUE, sep = ";", select = c("experiment_id",  :
  File '/mnt/workspace/hschult/jlu-bda-2020/data/download/linking_table.csv' does not exist or is non-readable. getwd()=='/mnt/workspace/hschult/jlu-bda-2020'
Calls: export_from_csv -> fread
Execution halted
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 207, in <module>
    main()
  File "bin/tf_analyzer.py", line 179, in main
    requested_data.pull_data()
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/generate_data.py", line 63, in pull_data
    self.download_data()
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/generate_data.py", line 108, in download_data
    raise Exception("export_from_csv.r could not download data")
Exception: export_from_csv.r could not download data

```

For some reason it seems to skip creating the linkage table and then throws an error that it does not exist in the next step.

**Comment by JonnyCodewalker** [comment]
Just to clarify, no linking_table.csv is created in the download folder?
Also, what are the parameters that tf_analyzer was called with?

**Comment by hschult** [comment]
Do you mean `data/download`? That one is empty.
Also, I set no parameters so the default is used for everything

**Comment by JonnyCodewalker** [comment]
Thank you.
It seems that with default arguments csv.r silently fails. I'll add a check to ensure the csv is created before the wrapper continues, but we still need to investigate why and where csv.r fails.

**Comment by Jasmin-Walter** [comment]
The Issue was caused by biosources that got a single quote in their names like "zymbal's gland". We inserted a backslach in front of the single quote so that it should work now.

The default parameters for tf_analyzer are: 
-g hg19
-b all (= all available on deepblue)
-t all (= all available on deepblue)
-c all (= all chromosomes available for hg19)
-w 50
-o path of the repository
