### ISSUE TITLE
Exception: csv.r could not create CSV

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#34]
The command: `python bin/tf_analyzer.py -g mm10 -b lung -t pax5 -c chr4`
The output:
```
python bin/tf_analyzer.py -g mm10 -b lung -t pax5 -c chr4
verifying chromosomes ...
verifying biosources ...
verifying epigenetic marks ...
Error in create_linking_table(args$genome, args$chromosomes, args$biosources,  :
  object 'csv_data' not found
In addition: Warning message:
In create_linking_table(args$genome, args$chromosomes, args$biosources,  :
  hg19: No CHIP-seq data available for given arguments
Execution halted
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 207, in <module>
    main()
  File "bin/tf_analyzer.py", line 179, in main
    requested_data.pull_data()
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/generate_data.py", line 62, in pull_data
    self.generate_csv()
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/generate_data.py", line 90, in generate_csv
    raise Exception("csv.r could not create CSV")
Exception: csv.r could not create CSV
```

So my guess would be that there simply is no CHIP-seq data available, but why does the warning say hg19? 

Additional info:
The linking table from the hg19, kidney, ar, chr1 run is still present. Could it be related to the linking table?

**Comment by Jasmin-Walter** [comment]
The genome was not passed to csv.r, which resulted in always using the default genome hg19. The error is now fixed.
