### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#35]
Since commit 2b598fcd60700f001bc8ec41e12ebd8af884ae1f I get following error:

```
python bin/tf_analyzer.py -g hg19 -b kidney -t ar -c chr1
....
....
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 207, in <module>
    main()
  File "bin/tf_analyzer.py", line 179, in main
    requested_data.pull_data()
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/generate_data.py", line 69, in pull_data
    self.normalize()
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/generate_data.py", line 192, in normalize
    normalize_all(norm_csv)
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/scripts/normalize_signal_values.py", line 133, in normalize_all
    min_max_scale_file(file_paths[j], log_file_paths[j],
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/scripts/normalize_signal_values.py", line 308, in min_max_scale_file
    frst_interval = bw.intervals(chrom, 0, 1)[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kmlr81** [comment]
this was an error with empty .ln files being created for bigwig files, because the skript didn't properly check, if bw files were empty to begin with or not. That problem should have been solved with Jasmin's latest push to dev. Testing has shown no further occurrence of the error.
