### ISSUE TITLE
Analysis impossible without internet

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#37]
Call: `python bin/tf_analyzer.py -h`

Error:
```
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 205, in <module>
    main()
  File "bin/tf_analyzer.py", line 49, in main
    genome_choices = [genome[1].lower() for genome in server.list_genomes(user_key)[1]]
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/hschult/.conda/tf_analyzer/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
When there is no connection possible to the server, for example, due to no internet connection, it is not possible to even show the help message. It would be nice to be able to at least work on the already downloaded data. And an error with a more meaningful message than the above would also be nice.

**Comment by Jasmin-Walter** [comment]
The script has been rewritten so that the help is now output without a required connection to the Internet. 
The program has also been extended with an offline mode. In case of no internet connection or if the DeepBlue server is down, the analysis can be run with the --offline parameter for already downloaded data.
