### ISSUE TITLE
conversion and normalization problems

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#38]
Call: `python bin/tf_analyzer.py -g mm9 -b liver`

Warnings:
```
validating files
Couldn't open /mnt/workspace/hschult/jlu-bda-2020/data/chromsizes/mm9.chrom.sizes
Couldn't open /mnt/workspace/hschult/jlu-bda-2020/data/chromsizes/mm9.chrom.sizes
Couldn't open /mnt/workspace/hschult/jlu-bda-2020/data/chromsizes/mm9.chrom.sizes
Couldn't open /mnt/workspace/hschult/jlu-bda-2020/data/chromsizes/mm9.chrom.sizes
```
...
```
unrecognized file format
unexpected file: ENCFF002ADS.chr1 chr1
unrecognized file format
unexpected file: ENCFF002ADS.chr2 chr2
unrecognized file format
unexpected file: ENCFF002ADS.chr3 chr3
unrecognized file format
unexpected file: ENCFF002ADS.chr4 chr4
unrecognized file format
unexpected file: ENCFF002ADS.chr5 chr5
```
...

Error:
```
76 of 152files were successfully normalised. If not all files were normalised, check logging for further information.
{'gata4', 'polr2a', 'ctcf'}
{'liver'}
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 205, in <module>
    main()
  File "bin/tf_analyzer.py", line 176, in main
    requested_data.pull_data()
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/generate_data.py", line 70, in pull_data
    self.generate_dictionaries()
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/generate_data.py", line 199, in generate_dictionaries
    parse(path)
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/scripts/generate_pickle.py", line 76, in parse
    for f in os.listdir(os.path.join(data_path, genome, biosource, 'atac-seq')):
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/workspace/hschult/jlu-bda-2020/data/mm9/liver/atac-seq'
```

Log:
```
INFO:root:['mm9', 'liver', 'aars', 'aatf', 'abcf1', 'aco1', 'adar', 'adnp2', 'aff1', 'aff4', 'aggf1', 'ago1', 'ago2', 'ago3', 'ahctf1', 'ahr', 'akap1', 'akap8', 'akap8l', 'apobec3b', 'apobec3c', 'ar', 'arid1a', 'arid1b', 'arid2', 'arid3a', 'arid3b', 'arnt', 'arnt2', 'arntl', 'arntl2', 'ascc1', 'ascl1', 'ash1l', 'ash2l', 'asxl1', 'atf1', 'atf2', 'atf3', 'atf4', 'atf6', 'atf7', 'atp5c1', 'atrx', 'auh', 'bach1', 'bach2', 'barx1', 'batf', 'batf3', 'bbx', 'bccip', 'bcl10', 'bcl11a', 'bcl3', 'bcl6', 'bclaf1', 'bcor', 'bdp1', 'bhlhe40', 'bhlhe41', 'bmi1', 'brca1', 'brd4', 'brd9', 'brf1', 'brf2', 'bud13', 'calr', 'camta1', 'carm1', 'casp8ap2', 'cbfa2t2', 'cbfa2t3', 'cbfb', 'cbx1', 'cbx2', 'cbx3', 'cbx3phospho', 'cbx4', 'cbx5', 'cbx7', 'cbx8', 'ccar1', 'ccar2', 'ccnt1', 'ccnt2', 'cdc5l', 'cdk9', 'cdkn1b', 'cdx1', 'cdx2', 'cebpa', 'cebpb', 'cebpd', 'cebpe', 'cebpz', 'celf1', 'chd1', 'chd2', 'chd3', 'chd4', 'chd7', 'cirbp', 'ckap4', 'clock', 'cnot7', 'cnot8', 'cpsf6', 'cpsf7', 'creb1', 'creb3l1', 'crebbp', 'crebl2', 'crem', 'cstf2', 'cstf2t', 'ctbp1', 'ctbp2', 'ctcf', 'ctcfl', 'ctnnb1', 'cux1', 'cxxc1', 'dazap1', 'ddit3', 'ddx1', 'ddx19b', 'ddx20', 'ddx21', 'ddx24', 'ddx27', 'ddx28', 'ddx3x', 'ddx42', 'ddx47', 'ddx5', 'ddx51', 'ddx52', 'ddx55', 'ddx59', 'ddx6', 'deaf1', 'dek', 'dgcr8', 'dhx30', 'dicer1', 'dkc1', 'dmc1', 'dmrt2', 'dnajc2', 'dnajc21', 'dnmt1', 'dot1l', 'dpf2', 'dr1', 'drap1', 'drosha', 'e2f1', 'e2f2', 'e2f3', 'e2f4', 'e2f6', 'e2f7', 'e2f8', 'ebf1', 'eed', 'eef2', 'eftud2', 'egfp-atf1', 'egfp-cebpb', 'egfp-creb3', 'egfp-ddx20', 'egfp-dido1', 'egfp-etv1', 'egfp-fos', 'egfp-gata2', 'egfp-hdac8', 'egfp-hinfp', 'egfp-id3', 'egfp-ilk', 'egfp-irf1', 'egfp-irf9', 'egfp-junb', 'egfp-jund', 'egfp-klf1', 'egfp-klf13', 'egfp-mafg', 'egfp-nfe2l1', 'egfp-nr4a1', 'egfp-ptrf', 'egfp-pttg1', 'egfp-pygo2', 'egfp-rela', 'egfp-taf7', 'egfp-tead2', 'egfp-tsc22d4', 'egfp-znf24', 'egr1', 'egr2', 'ehf', 'ehmt2', 'eif2s1', 'eif2s2', 'eif3a', 'eif3d', 'eif3g', 'eif4a3', 'eif4b', 'eif4g1', 'eif4g2', 'elavl1', 'elf1', 'elf2', 'elf3', 'elf4', 'elk1', 'elk3', 'elk4', 'eomes', 'ep300', 'ep400', 'epas1', 'ercc3', 'erg', 'esf1', 'esr1', 'esr2', 'esrra', 'ets1', 'etv1', 'etv4', 'etv5', 'etv6', 'evx1', 'ewsr1', 'exosc9', 'ezh1', 'ezh2', 'fam120a', 'fam208a', 'fastkd1', 'fastkd2', 'ferd3l', 'fip1l1', 'fkbp4', 'fli1', 'fmr1', 'fos', 'fosb', 'fosl1', 'fosl2', 'foxa1', 'foxa2', 'foxc1', 'foxd3', 'foxf1', 'foxf2', 'foxh1', 'foxj2', 'foxk1', 'foxk2', 'foxm1', 'foxo1', 'foxo4', 'foxp1', 'foxp2', 'foxp3', 'foxq1', 'foxr2', 'fubp3', 'fus', 'fxr1', 'fxr2', 'g3bp1', 'g3bp2', 'gabpa', 'gata1', 'gata2', 'gata3', 'gata4', 'gata6', 'gatad1', 'gemin5', 'gfi1b', 'gli2', 'glyr1', 'gmeb2', 'gnb2l1', 'gnl3', 'goat-igg-control', 'grhl1', 'grhl2', 'grhl3', 'grsf1', 'grwd1', 'gtf2b', 'gtf2f1', 'gtf2i', 'gtf3c2', 'gzf1', 'h2afz', 'h3ac', 'ha-e2f1', 'hand1', 'hand2', 'hcfc1', 'hdac1', 'hdac2', 'hdac3', 'hdac6', 'hdac8', 'hdgf', 'hes4', 'hes5', 'hes7', 'hesx1', 'hey1', 'heyl', 'hhex', 'hic2', 'hif1a', 'hivep3', 'hltf', 'hmbox1', 'hmgn1', 'hmgn3', 'hnf1a', 'hnf1b', 'hnf4a', 'hnf4g', 'hnrnpa0', 'hnrnpa1', 'hnrnpa2b1', 'hnrnpab', 'hnrnpc', 'hnrnpd', 'hnrnpf', 'hnrnph1', 'hnrnpk', 'hnrnpl', 'hnrnpm', 'hnrnpu', 'hnrnpul1', 'hoxa11', 'hoxa13', 'hoxa4', 'hoxa5', 'hoxa6', 'hoxa9', 'hoxb1', 'hoxb2', 'hoxb4', 'hoxb5', 'hoxb6', 'hoxb7', 'hoxb8', 'hoxc11', 'hoxc13', 'hoxc8', 'hoxc9', 'hoxd1', 'hoxd11', 'hoxd13', 'hoxd4', 'hoxd9', 'hsf1', 'hsf2', 'hspd1', 'id1', 'id2', 'id3', 'id4', 'igf2bp1', 'igf2bp2', 'igf2bp3', 'ikzf1', 'ikzf5', 'ilf2', 'ilf3', 'ing5', 'irf1', 'irf2', 'irf3', 'irf4', 'irf5', 'irf8', 'irf9', 'irx2', 'irx5', 'isl2', 'jarid2', 'jazf1', 'jun', 'junb', 'jund', 'kat2a', 'kat2b', 'kat5', 'kat7', 'kat8', 'kcmf1', 'kdm1a', 'kdm3a', 'kdm3b', 'kdm4a', 'kdm4b', 'kdm4c', 'kdm5a', 'kdm5b', 'kdm5c', 'kdm6a', 'khdrbs1', 'khsrp', 'kif1c', 'klf1', 'klf11', 'klf13', 'klf15', 'klf4', 'klf5', 'klf6', 'kmt2a', 'kmt2c', 'kmt2d', 'krr1', 'l3mbtl2', 'larp4', 'larp7', 'lcor', 'lcorl', 'ldb1', 'lef1', 'lhx2', 'lhx4', 'lhx5', 'lhx6', 'lin28b', 'lmna', 'lmnb1', 'lmo2', 'lsm11', 'lyl1', 'mafb', 'maff', 'mafg', 'mafk', 'magoh', 'mark2', 'matr3', 'max', 'maz', 'mbd2', 'mbd3', 'mbd4', 'mcm3', 'mecp2', 'med1', 'med26', 'mef2a', 'mef2b', 'mef2c', 'meis1', 'men1', 'meox2', 'metap2', 'mitf', 'mixl1', 'mllt1', 'mllt3', 'mouse-igg-control', 'msc', 'msi2', 'mta3', 'mtf1', 'mtpap', 'mxd3', 'mxi1', 'myb', 'mybl1', 'mybl2', 'myc', 'mycn', 'myf6', 'mynn', 'myod1', 'myog', 'naa15', 'nanog', 'ncbp2', 'ncoa1', 'ncoa3', 'ncor1', 'ncor2', 'nelfe', 'neurod1', 'neurod2', 'nfat5', 'nfatc1', 'nfe2', 'nfe2l1', 'nfe2l2', 'nfe2l3', 'nfib', 'nfic', 'nfkb1', 'nfkb2', 'nfkbia', 'nfx1', 'nfya', 'nfyb', 'nfyc', 'nhlh1', 'nip7', 'nipbl', 'nkrf', 'nkx2-1', 'nkx2-3', 'nkx2-8', 'nkx3-1', 'nkx6-1', 'nol12', 'non-specific target control', 'nono', 'npm1', 'nr1d1', 'nr1h2', 'nr1h3', 'nr1h4', 'nr1i2', 'nr2c2', 'nr2e3', 'nr2f1', 'nr2f2', 'nr2f6', 'nr3c1', 'nr3c2', 'nr4a1', 'nr4a2', 'nr5a1', 'nr5a2', 'nrf1', 'nufip2', 'nup98', 'nusap1', 'orc2', 'otx2', 'ovol2', 'pa2g4', 'pabpc1', 'pabpc4', 'pabpn1', 'paf1', 'papola', 'parn', 'pax5', 'pax6', 'pax7', 'pax8', 'pbx1', 'pbx2', 'pbx3', 'pcbp1', 'pcbp2', 'pcgf6', 'pdx1', 'pes1', 'pgr', 'phf6', 'phf8', 'pitx3', 'pkm', 'plag1', 'pml', 'pnpt1', 'polr2a', 'polr2aphosphos2', 'polr2aphosphos5', 'polr2b', 'polr2g', 'polr3a', 'polr3g', 'pou2af1', 'pou2f1', 'pou2f2', 'pou3f2', 'pou5f1', 'ppara', 'pparg', 'ppargc1a', 'ppig', 'ppil4', 'ppp1r8', 'prdm1', 'prdm14', 'prdm4', 'prox1', 'prpf6', 'prpf8', 'psip1', 'ptbp1', 'puf60', 'pum1', 'pum2', 'pus1', 'qki', 'rabbit-igg-control', 'rad21', 'rad51', 'rag1', 'rara', 'rat-igg-control', 'raver1', 'rb1', 'rbbp5', 'rbfox2', 'rbm15', 'rbm17', 'rbm22', 'rbm25', 'rbm27', 'rbm3', 'rbm34', 'rbm39', 'rbm47', 'rbpj', 'rcc2', 'rcor1', 'recql', 'rela', 'relb', 'rest', 'rfx2', 'rfx5', 'rfx7', 'ring1', 'rlf', 'rnf2', 'rpa2', 'rpl23a', 'rplp0', 'rps10', 'rps11', 'rps19', 'rps2', 'rps3', 'rps3a', 'rps5', 'rrp9', 'rtf1', 'runx1', 'runx2', 'runx3', 'rxra', 'safb2', 'sall4', 'sap30', 'sart3', 'satb1', 'sbds', 'serbp1', 'setd1a', 'setdb1', 'sf1', 'sf3a3', 'sf3b4', 'sfpq', 'sin3a', 'sin3b', 'sirt6', 'six1', 'six2', 'six5', 'ski', 'slbp', 'sltm', 'smad1', 'smad2', 'smad3', 'smad4', 'smad5', 'smarca1', 'smarca2', 'smarca4', 'smarca5', 'smarcb1', 'smarcc1', 'smarcc2', 'smarce1', 'smc3', 'smn1', 'smndc1', 'snai2', 'snapc4', 'snapc5', 'snd1', 'snrnp200', 'son', 'sox10', 'sox11', 'sox17', 'sox2', 'sox9', 'sp1', 'sp2', 'sp4', 'spdef', 'spi1', 'srebf1', 'srebf2', 'srf', 'srfbp1', 'srp68', 'srpk2', 'srsf1', 'srsf4', 'srsf5', 'srsf7', 'srsf9', 'ssb', 'ssrp1', 'stag2', 'stat1', 'stat2', 'stat3', 'stat4', 'stat5a', 'stat5b', 'stat6', 'stau1', 'stip1', 'sub1', 'suclg1', 'sugp2', 'sumo1', 'supt20h', 'supt5h', 'supt6h', 'supv3l1', 'suz12', 't', 't7-control', 'taf1', 'taf15', 'taf7', 'tal1', 'tardbp', 'tbl1xr1', 'tbp', 'tbrg4', 'tbx21', 'tcf12', 'tcf21', 'tcf3', 'tcf4', 'tcf7', 'tcf7l1', 'tcf7l2', 'tcfl5', 'tdrd3', 'tead1', 'tead4', 'terf1', 'terf2', 'tfam', 'tfap2a', 'tfap2c', 'tfap4', 'tfbs', 'tfcp2', 'tfdp1', 'tfip11', 'thap1', 'thap11', 'thap4', 'tia1', 'tial1', 'tlx1', 'tnrc6a', 'toe1', 'top1', 'tp53', 'tp63', 'tp73', 'tra2a', 'trim24', 'trim25', 'trim28', 'trim56', 'trip6', 'trove2', 'tshz1', 'tufm', 'u2af1', 'u2af2', 'ube2i', 'ube2l3', 'ubp1', 'ubtf', 'uchl5', 'upf1', 'upf2', 'usf1', 'usf2', 'vdr', 'vezf1', 'wdr5', 'whsc1', 'wiz', 'wrn', 'wrnip1', 'wwtr1', 'xbp1', 'xpo5', 'xrcc4', 'xrcc5', 'xrcc6', 'xrn2', 'yap1', 'ybx1', 'ybx3', 'ythdc2', 'ywhag', 'yy1', 'zbed1', 'zbtb10', 'zbtb11', 'zbtb16', 'zbtb17', 'zbtb2', 'zbtb24', 'zbtb33', 'zbtb39', 'zbtb4', 'zbtb44', 'zbtb48', 'zbtb7a', 'zc3h11a', 'zc3h8', 'zeb1', 'zfhx4', 'zfp42', 'zfx', 'zhx2', 'zkscan1', 'zmiz1', 'znf12', 'znf143', 'znf165', 'znf217', 'znf24', 'znf263', 'znf266', 'znf274', 'znf280d', 'znf281', 'znf3', 'znf384', 'znf395', 'znf486', 'znf516', 'znf581', 'znf622', 'znf639', 'znf644', 'znf711', 'znf750', 'znf76', 'znf83', 'znf84', 'znf92', 'zranb2', 'zscan5a', 'zscan5b', 'zzz3']
ERROR:root:The following error occurred while tryign to normalize the file /mnt/workspace/hschult/jlu-bda-2020/data/mm9/liver/chip-seq/gata4/ENCFF002ADS.chr1: <class 'ValueError'>
ERROR:root:The following error occurred while tryign to normalize the file /mnt/workspace/hschult/jlu-bda-2020/data/mm9/liver/chip-seq/gata4/ENCFF002ADS.chr2: <class 'ValueError'>
ERROR:root:The following error occurred while tryign to normalize the file /mnt/workspace/hschult/jlu-bda-2020/data/mm9/liver/chip-seq/gata4/ENCFF002ADS.chr3: <class 'ValueError'>
ERROR:root:The following error occurred while tryign to normalize the file /mnt/workspace/hschult/jlu-bda-2020/data/mm9/liver/chip-seq/gata4/ENCFF002ADS.chr4: <class 'ValueError'>
ERROR:root:The following error occurred while tryign to normalize the file /mnt/workspace/hschult/jlu-bda-2020/data/mm9/liver/chip-seq/gata4/ENCFF002ADS.chr5: <class 'ValueError'>
ERROR:root:The following error occurred while tryign to normalize the file /mnt/workspace/hschult/jlu-bda-2020/data/mm9/liver/chip-seq/gata4/ENCFF002ADS.chr6: <class 'ValueError'>
```
...

This is a big one. I think this is a problem coming from two things. First the chrom.size files are missing second some downloaded files are not converted. Here is one of the files that had conversion issues [ENCFF002ADR.chr1](https://github.com/loosolab/jlu-bda-2020/files/6228422/ENCFF002ADR.chr1.txt). The error also tells that the `atac-seq` folder is missing this might be a result of these things or another problem.
Let me know if you need any more information :)

**Comment by kmlr81** [comment]
The problem was caused solely by the chrom.sizes files not being downloaded. Since they are missing, the files could not be converted to bigWig and so there were files missing in the following steps of the pipeline. For ATAC seq we only use bigWig files, which explains the missing folder. The problem of the chrom.sizes files not being downloaded has now been fixed though.
