### ISSUE TITLE
TypeError: __init__() takes 8 positional arguments but 11 were given

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#41]
Call: `python bin/tf_analyzer.py -g mm9 -b liver -t gata4 polr2a -c chr1`

Error:
```
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 261, in <module>
    main()
  File "bin/tf_analyzer.py", line 228, in main
    requested_data = generate_data.DataConfig([args.genome], args.chromosome, args.biosource, args.tf,
TypeError: __init__() takes 8 positional arguments but 11 were given
```

**Comment by Jasmin-Walter** [comment]
The error was caused by the addition of some new parameters to tf_analyser.py which were not yet included in all scripts. The issue was solved with the commits referenced above.
