### ISSUE TITLE
Can not save plots due to file name length

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#46]
Call: `python bin/tf_analyzer.py -g mm9 -b liver`

Error:
```
mode auto: number of components is evaluated (components_fit.py)
Traceback (most recent call last):
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/tf_analyzer.py", line 261, in <module>
    main()
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/tf_analyzer.py", line 244, in main
    scripts.analyse_main.TF_analyser(n_comps=args.component_size, genome=args.genome, width=args.width,
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/scripts/analyse_main.py", line 150, in mainloop
    z = v.contourPlot(distribution, self.n_components, tf)
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/scripts/visualize_data.py", line 155, in contourPlot
    plt.savefig(vil_fig_path, format="svg")
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/site-packages/matplotlib/backends/backend_qt5agg.py", line 81, in print_figure
    super().print_figure(*args, **kwargs)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/site-packages/matplotlib/backends/backend_svg.py", line 1317, in print_svg
    with cbook.open_file_cm(filename, "w", encoding="utf-8") as fh:
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 423, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/hschult/.conda/tf_analyzer/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 408, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 36] File name too long: '/mnt/workspace/hschult/jlu-bda-2020/visualization/src/assets/img/liver_mm9/ctcf_chr1chr1_randomchr2chr3chr3_randomchr4chr4_randomchr5chr5_randomchr6chr7chr7_randomchr8chr8_randomchr9chr9_randomchr10chr11chr12chr13chr13_randomchr14chr15chr16chr16_randomchr17chr17_randomchr18chr19chrmchrun_randomchrxchrx_randomchrychry_random/Contour_ctcf_chr1chr1_randomchr2chr3chr3_randomchr4chr4_randomchr5chr5_randomchr6chr7chr7_randomchr8chr8_randomchr9chr9_randomchr10chr11chr12chr13chr13_randomchr14chr15chr16chr16_randomchr17chr17_randomchr18chr19chrmchrun_randomchrxchrx_randomchrychry_random.svg'
```

**Comment by jdetlef** [comment]
Sollte behoben sein
