### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#51]
Call: `python bin/tf_analyzer.py -g mm9 -b liver -t gata4 polr2a -c chr1`

Error:
```
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 266, in <module>
    main()
  File "bin/tf_analyzer.py", line 250, in main
    scripts.analyse_main.TF_analyser(n_comps=args.component_size, genome=args.genome, width=args.width,
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/scripts/analyse_main.py", line 140, in mainloop
    all_diffs = GmFit.getDifference(self, distribution, self.eval_size)
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/scripts/components_fit.py", line 184, in getDifference
    n_loc, n_stdwX, n_stdwY, n_weights = GmFit.emAnalyse(self, distribution, n_cgauss=z)
  File "/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/scripts/components_fit.py", line 130, in emAnalyse
    gmm.fit(distribution)
  File "/mnt/workspace/rwiegan/conda_envs/tf_analyzer/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "/mnt/workspace/rwiegan/conda_envs/tf_analyzer/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 220, in fit_predict
    X = _check_X(X, self.n_components, ensure_min_samples=2)
  File "/mnt/workspace/rwiegan/conda_envs/tf_analyzer/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 52, in _check_X
    X = check_array(X, dtype=[np.float64, np.float32],
  File "/mnt/workspace/rwiegan/conda_envs/tf_analyzer/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/mnt/workspace/rwiegan/conda_envs/tf_analyzer/lib/python3.8/site-packages/sklearn/utils/validation.py", line 637, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

```

**Comment by JonnyCodewalker** [comment]
This error could no longer be reproduced, please reopen if it is still occuring.
